// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2hLMN-hG_Zw5rN1vC6jEh24TPbiVmBqo',
    appId: '1:687783834952:web:402a5dffd8e0b5ca05af7d',
    messagingSenderId: '687783834952',
    projectId: 'gdgaast-7a5e7',
    authDomain: 'gdgaast-7a5e7.firebaseapp.com',
    storageBucket: 'gdgaast-7a5e7.firebasestorage.app',
    measurementId: 'G-C5Z9QNCVBV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj8F7cv-wC8cybF3CbAppL4ZPuipSwT8o',
    appId: '1:687783834952:android:0d41e7359c8a3c4305af7d',
    messagingSenderId: '687783834952',
    projectId: 'gdgaast-7a5e7',
    storageBucket: 'gdgaast-7a5e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCedQL6VhP9lc4ibeO_fosN8kuWl7k_mtM',
    appId: '1:687783834952:ios:702001741efd32a405af7d',
    messagingSenderId: '687783834952',
    projectId: 'gdgaast-7a5e7',
    storageBucket: 'gdgaast-7a5e7.firebasestorage.app',
    iosBundleId: 'org.agaafar.gdg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCedQL6VhP9lc4ibeO_fosN8kuWl7k_mtM',
    appId: '1:687783834952:ios:702001741efd32a405af7d',
    messagingSenderId: '687783834952',
    projectId: 'gdgaast-7a5e7',
    storageBucket: 'gdgaast-7a5e7.firebasestorage.app',
    iosBundleId: 'org.agaafar.gdg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2hLMN-hG_Zw5rN1vC6jEh24TPbiVmBqo',
    appId: '1:687783834952:web:b3c9a818580f911305af7d',
    messagingSenderId: '687783834952',
    projectId: 'gdgaast-7a5e7',
    authDomain: 'gdgaast-7a5e7.firebaseapp.com',
    storageBucket: 'gdgaast-7a5e7.firebasestorage.app',
    measurementId: 'G-QBD8385CYF',
  );
}
